language: r
warnings_are_errors: false
cache:
  packages: true
addons:
  apt:
    packages:
    - libudunits2-dev
    - libgsl0-dev
script:
- Rscript -e "rmarkdown::render_site()"
after_success:
  - curl -OL http://raw.githubusercontent.com/soztag/fau_deploy/master/deploy2karli.sh
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - bash deploy2karli.sh
  on:
    branch: master
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_25eefe9df2ee_key -iv $encrypted_25eefe9df2ee_iv -in karli_rsa.enc -out /tmp/karli_rsa -d
