language: r
warnings_are_errors: false
cache:
  packages: true
addons:
  apt:
    packages:
    - libudunits2-dev
    - libgsl0-dev
script:
- Rscript -e "rmarkdown::render_site()"
before_deploy:
- echo 'karli.rrze.uni-erlangen.de,131.188.16.138 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFHJVSekYKuF5pMKyHe1jS9mUkXMWoqNQe0TTs2sY1OQj379e6eqVSqGZe+9dKWzL5MRFpIiySRKgvxuHhaPQU4='
  >> $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_4f4c68a93cef_key -iv $encrypted_4f4c68a93cef_iv
  -in karli_rsa.enc -out /tmp/karli_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/karli_rsa
- ssh-add /tmp/karli_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet _site pfs400wm@karli.rrze.uni-erlangen.de:/proj/websource/docs/FAU/fakultaet/phil/www.datascience.phil.fau.de/websource/bsjobs
  on:
    branch: master
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_25eefe9df2ee_key -iv $encrypted_25eefe9df2ee_iv
  -in karli_rsa.enc -out ~\/.ssh/karli_rsa -d
