--- 
title: "Feelgood Managers und 'Bullshit Jobs'"
author: 
  - name: "Marco Blank"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Maximilian Held"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Verena Kasztantowicz"
    affiliation: "Humboldt-Universität zu Berlin (HU)"
  - name: "Horan Lee"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Manuel Nicklich"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Sabine Pfeiffer"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Stefan Sauer"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
  - name: "Amelie Tihlarik"
    affiliation: "Friedrich-Alexander Universität Erlangen-Nürnberg (FAU)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: held_library.bib
editor_options: 
  chunk_output_type: console
---

```{r, child="README.rmd"}
```

```{r setup, cache = FALSE, include = FALSE}
source("setup.R")
```

# Web Trends

Web Trends zu diesen einschlägigen Begriffen:

```{r terms}
fgm_terms <- tibble::tribble(
  ~term, ~short, ~lang,
  '"chief happiness officer"', "cho", "en-US",
  '"happiness officer"', "ho", "en-US",
  '"feelgood manager"', "fgm", "de-DE",
  '"feel good manager"', "fgm2", "de-DE",
  '"chef du bonheur"', "cdb", "fr-FR",
  '"directeur du bonheur"', "ddb", "fr-FR"
)
knitr::kable(x = fgm_terms, caption = "Relevante Suchbegriffe")
```


## Google Books NGrams

Google Books Daten stehen nur bis 2012 zur Verfügung; davor keine Ergebnisse für `chief happiness officer` oder `feelgood manager`.


## Google Trends

```{r, fig.cap="Google Trends (LOESSS)"}
fgm_gtrends <- gtrendsR::gtrends(
  keyword = fgm_terms$term[1:5], 
  time = "all", 
  low_search_volume = TRUE
)
# country is mostly france
# region and city is paris, nothing much else
ggplot(
  data = fgm_gtrends$interest_over_time,
  mapping = aes(
    x = date,
    y = hits,
    color = keyword
  )
) +
  geom_smooth(formula = y ~ x, method = "loess", se = TRUE, na.rm = TRUE, span = 0.3) +
  ylim(0, 100) +  # because google trends are indexed to 100
  scale_x_date(date_breaks = "1 year") + 
  guides(color = guide_legend(ncol = 2)) + 
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, hjust = 1))
```


## Twitter Trends

```{r twitter_grab, eval=FALSE, include=FALSE}
# this only works locally, because of keys
fgm_tweets <- rtweet::search_tweets2(
  q = fgm_terms$term,
  n = 1000,
  type = "mixed",
  include_rts = FALSE,
  parse = TRUE
)
readr::write_rds(x = fgm_tweets, path = "fgm_tweets.rds")
```

```{r twitter_load}
fgm_tweets <- readr::read_rds(path = "fgm_tweets.rds")
```




# Bibliografie
